apiVersion: v1
kind: Service
metadata:
  labels:
    app: brinq-auth-server
  name: brinq-auth-server
  namespace: default
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: brinq-auth-server
