apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistence
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage